config/routes.rb
Rails.application.routes.draw do
  get '/tasks/showAll', to: 'tasks#showAll'
  get '/activity_logs/:name', to: 'activity_logs#byUser'
  get '/activity_logs/:tagNumber', to: 'activity_logs#byCow'


  #get '/activity_logs/byCow/:tagNum', to: 'activity_logs#byCow'


  resources :locations
  resources :activity_logs
  resources :tasks
  resources :cattle_stats
  resources :cattle_stats
  root to: 'tasks#index'
  get '/users/sign_up', to: 'tasks#index'
  devise_for :users
  
end

app/models/cattle_stat.rb
class CattleStat < ActiveRecord::Base
	has_many :tasks
	accepts_nested_attributes_for :tasks
	#validates :tagNumber, :presence => true
	#validates :cowName, :presence => true
	#validates :dateOfBirth, :presence => true

	validates_presence_of :tagNumber
	validates_presence_of :cowName
	validates_presence_of :dateOfBirth




end

app/controllers/cattle_stats_controller.rb
class CattleStatsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  before_action :set_cattle_stat, only: [:show, :edit, :update, :destroy]

  # GET /cattle_stats
  # GET /cattle_stats.json
  def index
    @cattle_stats = CattleStat.all
  end

  # GET /cattle_stats/1
  # GET /cattle_stats/1.json
  def show
  end

  # GET /cattle_stats/new
  def new
    @cattle_stat = CattleStat.new
  end

  # GET /cattle_stats/1/edit
  def edit
  end

  def task
    @cattle_stat = CattleStat.set_cattle_stat
  end

  # POST /cattle_stats
  # POST /cattle_stats.json



  def create
    @cattle_stat = CattleStat.new(cattle_stat_params)
    @cattle_stat.insemDate = 0
    
    #create new activity 
    @new_log = ActivityLog.new()
    @new_log.task = 'Add New Cattle'
    @new_log.user = current_user.name
    @new_log.activityDate = Time.now
    @new_log.status = 'Added cow'
    @new_log.tagNum = @cattle_stat.tagNumber

    #create base tasks for new cow.
    @task = Task.new()
    @task.taskName = 'Wean'
    @task.status = 'Ready To Wean'
    if @cattle_stat.dateOfBirth != nil
      @task.tasksUnixDateTime = @cattle_stat.dateOfBirth + (209 * 24 * 60 * 60)
    end
    @task.start_time = Time.at(@task.tasksUnixDateTime)
    @task.complete = 0
    @task.taskTagNumber = @cattle_stat.tagNumber
    @task.save


    respond_to do |format|
      if @cattle_stat.save
        #save log
        @new_log.save
        format.html { redirect_to @cattle_stat, notice: 'Cattle stat was successfully created.' }
        format.json { render :show, status: :created, location: @cattle_stat }
      else
        format.html { render :new }
        format.json { render json: @cattle_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cattle_stats/1
  # PATCH/PUT /cattle_stats/1.json
  def update
    #create new activity 
    @new_log = ActivityLog.new()
    @new_log.task = 'Update Cattle'
    @new_log.user = 'temp'
    @new_log.activityDate = Time.now
    @new_log.status = 'updated cow'
    @new_log.tagNum = @cattle_stat.registrationNumber
    respond_to do |format|
      if @cattle_stat.update(cattle_stat_params)
        @new_log.save
        format.html { redirect_to @cattle_stat, notice: 'Cattle stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cattle_stat }
      else
        format.html { render :edit }
        format.json { render json: @cattle_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cattle_stats/1
  # DELETE /cattle_stats/1.json
  def destroy
    @cattle_stat.destroy
    respond_to do |format|
      format.html { redirect_to cattle_stats_url, notice: 'Cattle stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cattle_stat
      @cattle_stat = CattleStat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cattle_stat_params
      params.require(:cattle_stat).permit(:registrationNumber, :tagNumber, :maternalRegistrationNumber, :paternalRegistrationNumber, :status, :location, :isPregnant, :weight, :dateOfBirth, :sellDate, :nextPregnancyCheck, :vaccinationDate, :anticipatedBirthDate, :sex, :heatWindowStartDate, :cowName, :numOfStraws, :inHeat, :insemDate)
    end
end

app/helpers/cattle_stats_helper.rb
module CattleStatsHelper
end

app/views/cattle_stats/_form.html.erb
<%= form_for(@cattle_stat) do |f| %>
  <% if @cattle_stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cattle_stat.errors.count, "error") %> prohibited this cattle_stat from being saved:</h2>

      <ul>
      <% @cattle_stat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  Registration Number:  <%= f.number_field :registrationNumber %>
  </div>
  <div class="field">
    Tag Number:  <font color="red">*</font> <%= f.number_field :tagNumber, required: true %>
  </div>
  <div class="field">
    Cow Name:    <font color="red">*</font> <%= f.text_field :cowName, required: true  %>
  </div>
  <div class="field">
    Maternal Registration Number:   <%= f.number_field :maternalRegistrationNumber %>
  </div>
  <div class="field">
   Paternal Registration Number: <%= f.number_field :paternalRegistrationNumber %>
  </div>
  <div class="field">
    Status(if any):  <%= f.text_field :status %>
  </div>
  <div class="field">
      Location 

      <% @locs = Location.all %>
      <% @names ||= [] %>
      <% @locs.each do |loc| %>
       <% @names.push(loc.shortName) %>
      <% end %>
      <% @names.sort! %>
     
      <%= f.select :location, @names %>
  </div>
  <div class="field">
    Is Pregnant?(0 for no, 1 for yes):  <%= f.number_field :isPregnant %>
  </div>
  <div class="field">
  Cow Is In Heat?(0 for no, 1 for yes):  <%= f.number_field :inHeat %>
  </div>
  <div class="field">
    Heat Window Start Date:   <%= f.number_field :heatWindowStartDate %>
  </div>
  
  <div class="field">
    Curren Weight:  <%= f.number_field :weight %>
  </div>
  <div class="field">
    DOB:  <font color="red">*</font> <%= f.number_field :dateOfBirth, required: true  %>
  </div>
  <div class="field">
    Sell Date:  <%= f.number_field :sellDate %>
  </div>
  <div class="field">
    Next Pregnancy Check:  <%= f.number_field :nextPregnancyCheck %>
  </div>
  <div class="field">
    Last Insemination Date:  <%= f.number_field :insemDate %>
  </div>
  <div class="field">
    Last Vaccination Date:   <%= f.number_field :vaccinationDate %>
  </div>
  <div class="field">
    Anticipated Birthing Date:  <%= f.number_field :anticipatedBirthDate %>
  </div>
  <div class="field">
    Sex:    <%= f.text_field :sex %>
  </div>
  <div class="field">
  Number of Children:   <%= f.number_field :numberOfChildren %>
  </div>
  <div class="field">
    Number of Available Straws:   <%= f.number_field :numOfStraws %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cattle_stats/edit.html.erb
<p>Editing Cattle Stat: <font color="red">*</font> = required field.<p>

<%= render 'form' %>

<%= link_to 'Show', @cattle_stat %> |
<%= link_to 'Back', cattle_stats_path %>

app/views/cattle_stats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cattle Stats</h1>

<table border = 1>
  <thead>
    <tr>
      <th>Reg Num</th>
      <th>Tag Num</th>
      <th>Name</th>
      <th>Mom</th>
      <th>Dad</th>
      <th>Status</th>
      <th>Location</th>
      <th>Is Pregnant</th>
      <th>In Heat</th>
      <th>heat window start date</th>
      <th>Insemination Date</th>
      <th>Weight</th>
      <th>DOB</th>
      <th>Sell date</th>
      <th>next preg check</th>
      <th>vaccination date </th>
      <th>anticipated DOB</th>
      <th>Sex</th>
      <th>Number of Straws</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cattle_stats.each do |cattle_stat| %>
      <tr>
        <td><%= cattle_stat.registrationNumber %></td>
        <td><%= cattle_stat.tagNumber %></td>
        <td><%= cattle_stat.cowName %></td>
        <td><%= cattle_stat.maternalRegistrationNumber %></td>
        <td><%= cattle_stat.paternalRegistrationNumber %></td>
        <td><%= cattle_stat.status %></td>
        <td><%= cattle_stat.location %></td>
        <td><%= cattle_stat.isPregnant %></td>
        <td><%= cattle_stat.inHeat %></td>
        <td><%= Time.at(cattle_stat.heatWindowStartDate).strftime("%B %e, %Y") %></td>
      <% if cattle_stat.insemDate != nil %>
        <td><%= Time.at(cattle_stat.insemDate).strftime("%B %e, %Y ") %></td>
      <% else %>
        <td>0</td>
      <% end %>
        <td><%= cattle_stat.weight %></td>
        <td><%= Time.at(cattle_stat.dateOfBirth).strftime("%B %e, %Y ") %></td>
        <td><%= Time.at(cattle_stat.sellDate).strftime("%B %e, %Y") %></td>
        <td><%= Time.at(cattle_stat.nextPregnancyCheck).strftime("%B %e, %Y") %></td>
        <td><%= Time.at(cattle_stat.vaccinationDate).strftime("%B %e, %Y") %></td>
        <td><%= Time.at(cattle_stat.anticipatedBirthDate).strftime("%B %e, %Y ") %></td>
        <td><%= cattle_stat.sex %></td>
        <td><%= cattle_stat.numOfStraws %></td>
        <td><%= link_to 'Show', cattle_stat %></td>
        <td><%= link_to 'Home', '/' %></td>
        <td><%= link_to 'Edit', edit_cattle_stat_path(cattle_stat) %></td>
        <td><%= link_to 'Destroy', cattle_stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Cow', new_cattle_stat_path %>

app/views/cattle_stats/new.html.erb
<p>Enter new cow information: <font color="red">*</font> = required field.</p>

<%= render 'form' %>

<%= link_to 'Back', cattle_stats_path %>

app/views/cattle_stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Registration Number:</strong>
  <%= @cattle_stat.registrationNumber %>
</p>

<p>
  <strong>Tag Number:</strong>
  <%= @cattle_stat.tagNumber %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cattle_stat.cowName %>
</p>

<p>
  <strong>Maternalr Registration Number:</strong>
  <%= @cattle_stat.maternalRegistrationNumber %>
</p>

<p>
  <strong>Paternal Registation Number:</strong>
  <%= @cattle_stat.paternalRegistrationNumber %>
</p>

<p>
  <strong>Status:</strong>
  <%= @cattle_stat.status %>
</p>

<p>
  <strong>Location:</strong>
  <%= @cattle_stat.location %>
</p>

<p>
  <strong>Is Pregnant:</strong>
  <%= @cattle_stat.isPregnant %>
</p>
<strong>Insemination Date:</strong>
  <%= Time.at(@cattle_stat.insemDate) %>
</p>

<p>
  <strong>Heat Window Start Date(remember to change this to the actual window size:</strong>
  <%= @cattle_stat.heatWindowStartDate %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @cattle_stat.weight %>
</p>

<p>
  <strong>Date of Birth:</strong>
  <%= Time.at(@cattle_stat.dateOfBirth).strftime("%B %e, %Y at %I:%M %p") %>
</p>

<p>
  <strong>Sell Date:</strong>
  <%= Time.at(@cattle_stat.sellDate).strftime("%B %e, %Y at %I:%M %p") %>
</p>

<p>
  <strong>Next Pregnancy Check:</strong>
  <%= Time.at(@cattle_stat.nextPregnancyCheck).strftime("%B %e, %Y at %I:%M %p") %>
</p>

<p>
  <strong>Vaccinationdate:</strong>
  <%= Time.at(@cattle_stat.vaccinationDate).strftime("%B %e, %Y at %I:%M %p") %>
</p>

<p>
  <strong>Anticipated Birthdate:</strong>
  <%= Time.at(@cattle_stat.anticipatedBirthDate).strftime("%B %e, %Y at %I:%M %p") %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @cattle_stat.sex %>
</p>
<p>
  <strong>Number of Children:</strong>
  <%= @cattle_stat.numberOfChildren %>
</p>

<p>
  <strong>Number of Srtaws:</strong>
  <%= @cattle_stat.numOfStraws %>
</p>

<%= link_to 'Edit', edit_cattle_stat_path(@cattle_stat) %> |
<%= link_to 'Back', cattle_stats_path %> |
<%= link_to 'Home', '/' %>