config/routes.rb
Rails.application.routes.draw do
  get '/tasks/showAll', to: 'tasks#showAll'
  get '/activity_logs/:name', to: 'activity_logs#byUser'
  get '/activity_logs/:tagNumber', to: 'activity_logs#byCow'


  #get '/activity_logs/byCow/:tagNum', to: 'activity_logs#byCow'


  resources :locations
  resources :activity_logs
  resources :tasks
  resources :cattle_stats
  resources :cattle_stats
  root to: 'tasks#index'
  get '/users/sign_up', to: 'tasks#index'
  devise_for :users
  
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Rails bootstrap", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<%= link_to "Calendar", tasks_path, :class => 'navbar-link' %>
      | <%= link_to 'Add New Cow', new_cattle_stat_path, :class => 'navbar-link' %>
      | <%= link_to 'User Activity Log', activity_logs_path, :class => 'navbar-link' %>
      | <%= link_to 'Cow Historical Data', activity_logs_path, :class => 'navbar-link' %>
      | <%= link_to 'Add New Base Task', new_task_path, :class => 'navbar-link' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Cattle" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Cattle" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>

  </head>
  <body>
    <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      <% if user_signed_in? %>

      | <%= link_to "Calendar", tasks_path, :class => 'navbar-link' %>
      | <%= link_to 'View All Cows', cattle_stats_path, :class => 'navbar-link' %>
      | <%= link_to 'Add New Cow', new_cattle_stat_path, :class => 'navbar-link' %>
      | <%= link_to 'User Activity Log and Cattle History Data', activity_logs_path, :class => 'navbar-link' %>
      | <%= link_to 'Add New Base Task', new_task_path, :class => 'navbar-link' %>
      <% end %>

    <header>
      <%= render 'layouts/navigation' %>
      </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>

    </main>
    <p class="navbar-text pull-right">
    
  </body>
</html>